name: Testing the push action

on:
  schedule:
    - cron: '30 3 * * *'
  push:
    paths:
      - .github/workflows/test-push.yml

jobs:
  commitAndPush:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Make changes
        run: date -u +"%Y-%m-%d %H:%M:%S" >> run.log
      -
        name: Commit changes
        run: |
          git config --local user.email office@${{ github.actor }}.com
          git config --local user.name ${{ github.actor }}
          git add run.log
          git commit -m "Update run log"
      -
        name: Push changes
        uses: ad-m/github-push-action@master
